#!/bin/bash
# dracut module-setup for bpir-verify
#
# Enforces the binary-hash pin baked into the UKI's kernel cmdline by
# build_uki.sh. Without this hook, `bpir.expected_binary_sha256=...`
# in /proc/cmdline is just a value committed to MEASUREMENT — no code
# on the box actually checks the on-disk binary against it. With this
# hook, a binary-tamper attempt forces the next boot into emergency
# shell instead of silently running with stale or compromised code.
#
# Installed at /usr/lib/dracut/modules.d/95bpir-verify/ by
# scripts/build_uki.sh and pulled into the per-UKI initramfs via
# `dracut --add bpir-verify` (so it does NOT pollute future
# autogenerated initrds for unrelated kernel updates).

# shellcheck shell=bash

check() {
    return 0
}

depends() {
    echo "systemd"
    return 0
}

install() {
    inst_hook pre-pivot 90 "$moddir/bpir-verify.sh"
    # Tools used by bpir-verify.sh. dracut's busybox subset doesn't
    # always include sha256sum, so pull it in explicitly along with
    # the text utilities our parser needs.
    inst_multiple sha256sum grep awk cut
}
