#!/usr/bin/env bash
# Partition the protocol-and-persistence CI contract into independently cached
# lanes. Keep commands here explicit: the workflow semantic gate inventories
# them, while YAML owns only runner setup, cache statistics, and artifacts.
set -euo pipefail

usage() {
  cat <<'USAGE'
usage: scripts/payment-v1-ci-lane.sh --lane <core|runtime-default-security|runtime-features|issuer-directory-tools>
USAGE
}

if [[ $# -eq 1 && $1 == --help ]]; then
  usage
  exit 0
fi
[[ $# -eq 2 && $1 == --lane ]] || { usage >&2; exit 2; }
lane=$2
# GitHub Actions supplies RUNNER_TEMP; retain a bounded local fallback for
# syntax/help and intentional local lane runs.
runner_temp=${RUNNER_TEMP:-${TMPDIR:-/tmp}}

case "$lane" in
  core)
    cargo test --timings --locked --offline -p pir-channel -p pir-strict-https -p pir-private-files -p pir-rollback-authority-protocol -p pir-rollback-authority-client -p pir-rollback-authority-store -p pir-service-protocol -p pir-service-store -p pir-payment-crypto -p pir-lightning-backend -p pir-issuer-store -p pir-issuer-core -p pir-issuer-credentials -p pir-issuer-clearing -p pir-issuer-service -p pir-provider-clearing-client -p pir-cashu-client -p pir-cashu-custody -p pir-arc-adapter -p pir-directory-nostr -p bitcoinpir-directory-relay -p bitcoinpir-cln-rpc-guard -p pir-runtime-core -p pir-sdk-client -p pir-sdk-wasm -p payment-issuer -p rollback-authority -p bpir-admin
    rustup_home="$(rustup show home)"; cargo_home="${CARGO_HOME:-${HOME}/.cargo}"; cargo_bin="$(command -v cargo)"; root_test_target="$(mktemp -d "${runner_temp}/bpir-admin-root-target.XXXXXX")"; trap 'sudo rm -rf -- "$root_test_target"' EXIT
    sudo env PATH="$PATH" RUSTUP_HOME="$rustup_home" CARGO_HOME="$cargo_home" CARGO_TARGET_DIR="$root_test_target" BPIR_REQUIRE_ROOT_CREDENTIAL_TEST=1 "$cargo_bin" test --locked --offline -p bpir-admin lightning_staging::tests::protected_config_real_linux_uid_gid_and_mode_contract -- --exact --nocapture
    cargo test --locked --offline -p pir-payment-crypto --features provider-store --test provider_store_bat_adapter
    cargo test --locked --offline -p pir-arc-adapter --features provider-store
    cargo clippy --timings --locked --offline --all-targets --no-deps -p pir-strict-https -p pir-private-files -p pir-rollback-authority-protocol -p pir-rollback-authority-client -p pir-rollback-authority-store -p pir-service-protocol -p pir-service-store -p pir-payment-crypto -p pir-lightning-backend -p pir-issuer-store -p pir-issuer-core -p pir-issuer-credentials -p pir-issuer-clearing -p pir-issuer-service -p pir-provider-clearing-client -p pir-cashu-client -p pir-cashu-custody -p pir-arc-adapter -p pir-directory-nostr -p bitcoinpir-directory-relay -p bitcoinpir-cln-rpc-guard -p payment-issuer -p rollback-authority -p bpir-admin -- -D warnings
    cargo test --locked --offline -p pir-service-protocol --test payment_v1_adversarial; cargo test --locked --offline -p pir-runtime-core --test service_admission_adversarial; cargo test --locked --offline -p pir-strict-https; cargo test --locked --offline -p pir-rollback-authority-protocol; cargo test --locked --offline -p pir-rollback-authority-client; cargo test --locked --offline -p pir-rollback-authority-store; cargo test --locked --offline -p rollback-authority
    ;;
  runtime-default-security)
    cargo check --timings --locked --offline -p runtime --bin unified_server; cargo test --locked --offline -p runtime --lib hint_pool; cargo test --locked --offline -p runtime --bin unified_server
    cargo test --locked --offline -p runtime --features test-only-unsafe-query-logging --bin unified_server service_admission_dispatch_tests::explicit_debug_feature_cli_parser_recognizes_unsafe_logging_flag -- --exact
    cargo clippy --locked --offline -p runtime --bin unified_server --test payment_v1_process_e2e --test payment_v1_methods_process_e2e --test payment_v1_harmony_pool_process_e2e --test payment_v1_onion_process_e2e --no-deps -- -D warnings
    cargo clippy --locked --offline -p runtime --features test-only-unsafe-query-logging --bin unified_server --no-deps -- -D warnings
    cargo test --locked --offline -p runtime --test payment_v1_process_e2e; cargo test --locked --offline -p runtime --test payment_v1_methods_process_e2e; cargo test --locked --offline -p runtime --test payment_v1_harmony_pool_process_e2e; cargo test --locked --offline -p runtime --test payment_v1_onion_process_e2e
    cargo test --locked --offline -p pir-rollback-authority-client --features test-only-webpki-root test_only_webpki_root_requires_owner_only_regular_file; cargo test --locked --offline -p runtime --features remote-authority-process-e2e --test payment_v1_process_e2e remote_authority_process::remote_authority_real_process_tls_provider_e2e -- --exact; cargo test --locked --offline -p runtime --features remote-authority-process-e2e --test payment_v1_process_e2e three_authority_process::three_authority_real_process_topology_e2e -- --exact; cargo clippy --locked --offline -p runtime --features remote-authority-process-e2e --bin unified_server --test payment_v1_process_e2e --no-deps -- -D warnings; cargo test --locked --offline -p payment-issuer --features remote-authority-process-e2e --test remote_authority_process_e2e payment_issuer_remote_authority_real_process_tls_e2e -- --exact; cargo clippy --locked --offline -p payment-issuer --features remote-authority-process-e2e --all-targets --no-deps -- -D warnings
    log_file="$(mktemp "${runner_temp}/bpir-release-security.XXXXXX")"; trap 'rm -f -- "$log_file"' EXIT
    for spec in 'pir-strict-https test-only-webpki-root test-only-webpki-root must never be compiled into a production release' 'payment-issuer remote-authority-process-e2e test-only-webpki-root must never be compiled into a production release' 'runtime remote-authority-process-e2e test-only-webpki-root must never be compiled into a production release' 'runtime standard-cashu-process-e2e test-only-webpki-root must never be compiled into a production release' 'runtime shared-issuer-process-e2e test-only-webpki-root must never be compiled into a production release' 'runtime test-only-unsafe-query-logging feature `test-only-unsafe-query-logging` is restricted to Cargo'; do read -r package feature diagnostic <<<"$spec"; if cargo check --locked --offline --release -p "$package" --features "$feature" >"$log_file" 2>&1; then exit 1; fi; grep -F "$diagnostic" "$log_file" >/dev/null; if RUSTFLAGS='-C debug-assertions=yes' cargo check --locked --offline --release -p "$package" --features "$feature" >"$log_file" 2>&1; then exit 1; fi; grep -F "$diagnostic" "$log_file" >/dev/null; done
    ;;
  runtime-features)
    cargo test --timings --locked --offline --manifest-path vendor/bitcoinpir-oram/Cargo.toml; cargo test --locked --offline -p runtime --features cuckoo-oram --test payment_v1_tee_oram_process_e2e
    cargo test --locked --offline -p runtime --features standard-cashu-process-e2e --test payment_v1_standard_cashu_process_e2e standard_cashu_real_process_tls_two_provider_e2e -- --exact; cargo test --locked --offline -p runtime --features standard-cashu-process-e2e --test payment_v1_process_e2e all_non_receipt_methods_commit_before_real_harmony_query_and_replay_after_restart -- --exact; cargo test --locked --offline -p runtime --features standard-cashu-process-e2e --test payment_v1_harmony_pool_process_e2e all_non_receipt_methods_restore_pre_dispatch_and_burn_on_real_hint_dispatch -- --exact; cargo test --locked --offline -p runtime --features standard-cashu-process-e2e --test payment_v1_onion_process_e2e all_non_receipt_methods_commit_before_real_onion_job_and_replay_after_restart -- --exact; cargo test --locked --offline -p runtime --features cuckoo-oram,standard-cashu-process-e2e --test payment_v1_tee_oram_process_e2e all_non_receipt_methods_commit_before_real_tee_oram_and_replay_after_restart -- --exact
    log_file="$(mktemp "${runner_temp}/bpir-cashu-test-root-cli.XXXXXX")"; trap 'rm -f -- "$log_file"' EXIT; if cargo run --locked --offline -p runtime --bin unified_server -- --test-only-service-https-root-pem /does/not/exist >"$log_file" 2>&1; then exit 1; fi; grep -F 'unknown argument: --test-only-service-https-root-pem' "$log_file" >/dev/null
    issuer_e2e_target_dir="$PWD/target/payment-issuer-shared-e2e"; cargo build --timings --locked --offline -p payment-issuer --features test-only-fake-lightning --bin payment-issuer --target-dir "$issuer_e2e_target_dir"; cargo build --timings --locked --offline -p bpir-admin --bin bpir-admin --target-dir "$issuer_e2e_target_dir"; BITCOINPIR_PAYMENT_ISSUER_BIN="$issuer_e2e_target_dir/debug/payment-issuer" BITCOINPIR_BPIR_ADMIN_BIN="$issuer_e2e_target_dir/debug/bpir-admin" cargo test --locked --offline -p runtime --features shared-issuer-process-e2e --test payment_v1_shared_issuer_process_e2e
    cargo clippy --locked --offline -p runtime --features cuckoo-oram,shared-issuer-process-e2e --bin unified_server --test payment_v1_tee_oram_process_e2e --test payment_v1_standard_cashu_process_e2e --test payment_v1_process_e2e --test payment_v1_harmony_pool_process_e2e --test payment_v1_onion_process_e2e --test payment_v1_shared_issuer_process_e2e --no-deps -- -D warnings
    ;;
  issuer-directory-tools)
    cargo test --timings --locked --offline -p payment-issuer --features test-only-fake-lightning; cargo run --locked --offline -p payment-issuer --features test-only-fake-lightning -- serve-fake --help >/dev/null; cargo clippy --locked --offline -p payment-issuer --features test-only-fake-lightning --all-targets --no-deps -- -D warnings
    cargo test --locked --offline -p bitcoinpir-directory-relay --test payment_v1_two_relay_process_e2e two_relay_real_process_catalog_e2e -- --exact --ignored; cargo clippy --locked --offline -p bitcoinpir-directory-relay --test payment_v1_two_relay_process_e2e --no-deps -- -D warnings
    log_file="$(mktemp "${runner_temp}/bpir-fake-lightning-release.XXXXXX")"; trap 'rm -f -- "$log_file"' EXIT; if cargo run --locked --offline --release -p payment-issuer -- serve-fake --help >"$log_file" 2>&1; then exit 1; fi; grep -F "unrecognized subcommand 'serve-fake'" "$log_file" >/dev/null; if cargo check --locked --offline --release -p payment-issuer --features test-only-fake-lightning >"$log_file" 2>&1; then exit 1; fi; grep -F 'test-only-fake-lightning must never be compiled into a production release' "$log_file" >/dev/null; if RUSTFLAGS='-C debug-assertions=yes' cargo check --locked --offline --release -p payment-issuer --features test-only-fake-lightning >"$log_file" 2>&1; then exit 1; fi; grep -F 'test-only-fake-lightning must never be compiled into a production release' "$log_file" >/dev/null
    cargo test --locked --offline -p pir-cashu-client --features insecure-dev-sqlite-store --test cdk_nut03_interop --no-run
    fixture_root="$(mktemp -d "${runner_temp}/bpir-payment-v1-fixture.XXXXXX")"; trap 'rm -f -- "$log_file"; rm -rf -- "$fixture_root"' EXIT; scripts/fixtures/generate-payment-v1-no-funds.sh "$fixture_root/generated"; test -s "$fixture_root/generated/fixture.json"
    bash -n scripts/payment-v1-cdk-regtest-e2e.sh; grep -F 'standard_cashu_real_cdk_browser_provider_two_server_e2e' scripts/payment-v1-cdk-regtest-e2e.sh >/dev/null; grep -F 'standard_cashu_cdk_tls_proxy_subprocess' apps/server/tests/payment_v1_standard_cashu_process_e2e.rs >/dev/null; grep -F 'total_mint_amount=$((expected_amount * 2))' scripts/payment-v1-cdk-regtest-e2e.sh >/dev/null; bash -n scripts/payment-v1-cln-regtest-e2e.sh; bash scripts/payment-v1-cln-regtest-e2e.sh --help | grep -F -- '--acknowledge-local-regtest-only' >/dev/null; test -s web/e2e/payment-two-provider-cln-joined.spec.ts; test -s web/playwright.payment-cln-joined.config.ts; grep -F 'playwright.payment-cln-joined.config.ts' web/package.json >/dev/null; grep -F "BITCOINPIR_PAYMENT_TWO_PROVIDER_BACKEND = 'fake'" web/playwright.payment-two-provider.config.ts >/dev/null; grep -F "BITCOINPIR_PAYMENT_TWO_PROVIDER_BACKEND = 'cln-regtest'" web/playwright.payment-cln-joined.config.ts >/dev/null
    ;;
  *) usage >&2; exit 2 ;;
esac
